---
name: Publish
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pierotofy/set-swap-space@master
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - id: docker
        uses: docker/metadata-action@v4
        with:
          images: |
            mfinelli/ruby-imagemagick
            ghcr.io/mfinelli/ruby-imagemagick
      - uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            mfinelli/ruby-imagemagick:latest
            ghcr.io/mfinelli/ruby-imagemagick:latest
