---
name: Mirror to GitHub
on:
  push:
    branches:
      - master

jobs:
  main:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: metadata
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            mfinelli/ruby-imagemagick
            docker.pkg.github.com/mfinelli/docker-ruby-imagemagick/ruby-imagemagick
      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            mfinelli/ruby-imagemagick:latest
            docker.pkg.github.com/mfinelli/docker-ruby-imagemagick/ruby-imagemagick:latest
      - uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mfinelli/ruby-imagemagick
          short-description: "ruby:latest with imagemagick7"
